<center><h1>实验二 随机变量</h1></center>

## 姓名：林鹏&emsp;&emsp;班级：数科2194&emsp;&emsp;学号：202141084097

In [1]:
import numpy as np
from numpy.linalg import inv

In [2]:
A = np.array([2, -1, 4, 0, 1, -1, 1, 3, -2]).reshape((3, 3))    # 创建一个3阶方阵
A

array([[ 2, -1,  4],
       [ 0,  1, -1],
       [ 1,  3, -2]])

In [3]:
Ex = np.array([5, -2, 7])
Ex

array([ 5, -2,  7])

In [4]:
Vx = np.array([4, 1, 2, 1, 9, -3, 2, -3, 25]).reshape(3, 3, order="A")
Vx

array([[ 4,  1,  2],
       [ 1,  9, -3],
       [ 2, -3, 25]])

In [5]:
D = np.sqrt(np.diag(np.diag(Vx)))   # np.sqrt()是平方根函数
D

array([[2., 0., 0.],
       [0., 3., 0.],
       [0., 0., 5.]])

In [6]:
Ey = A.dot(Ex)
Ey = Ey.reshape(3,-1)
Ey


array([[ 40],
       [ -9],
       [-15]])

In [7]:
Vy = A.dot(Vx).dot(A.T)
Vy

array([[ 477, -126, -256],
       [-126,   40,   91],
       [-256,   91,  219]])

In [8]:
Rx = inv(D).dot(Vx).dot(inv(D))
Rx

array([[ 1.        ,  0.16666667,  0.2       ],
       [ 0.16666667,  1.        , -0.2       ],
       [ 0.2       , -0.2       ,  1.        ]])

## 验证 2.9

$ 公式：V(y) = \boldsymbol{A}V(x)\boldsymbol{A}^\prime$

In [9]:
import numpy as np
import numpy.linalg as LA

In [10]:
Vx = np.array([[9, 1, -2], [1, 20, 3], [-2, 3, 12]]).reshape((3,3), order='A')
Vx

array([[ 9,  1, -2],
       [ 1, 20,  3],
       [-2,  3, 12]])

In [11]:
A = np.array([[2,3, 1], [1,-2, 5], [0, 1, -1]]).reshape((3,3), order='A')
A

array([[ 2,  3,  1],
       [ 1, -2,  5],
       [ 0,  1, -1]])

In [12]:
Vy = A.dot(Vx).dot(A.T)
Vy

array([[250, -26,  48],
       [-26, 305, -76],
       [ 48, -76,  26]])

## 验证2.12

相关矩阵$R=(\rho)_{ij}$ 和协方差矩阵 $\sum= {\sigma}_{ij}$ 之间有关系式\
$R=D^{-1}\sum D^{-1}$\
其中$D=diag(\sqrt{\sigma_{11}}, \sqrt{\sigma_{22}}, \ldots, \sqrt{\sigma_{pp}})$

In [13]:
sigma = np.array([[16, -4, 3], [-4, 4, -2], [3, -2, 9]]).reshape((3, 3), order='A')
sigma

array([[16, -4,  3],
       [-4,  4, -2],
       [ 3, -2,  9]])

In [14]:
D = np.diag(np.sqrt(np.diag(sigma)))
D

array([[4., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [15]:
R = LA.inv(D).dot(sigma).dot(LA.inv(D))
R

array([[ 1.        , -0.5       ,  0.25      ],
       [-0.5       ,  1.        , -0.33333333],
       [ 0.25      , -0.33333333,  1.        ]])